[core]
reloadable = true
order = 0

[package]
version = "0.2.0"
category = "Simulation"
title = "Isaac Sim Property Extensions"
description = "Adds Isaac Sim Specific Property Utils"
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac", "property"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"omni.kit.uiapp" = {}
"omni.usd" = {}
"omni.kit.window.property" = {}
"omni.kit.property.usd" = {}
"omni.usd.schema.isaac" = {}

[[python.module]]
name = "omni.kit.property.isaac"