[core]
reloadable = true
order = 0

[package]
version = "1.2.3"
category = "Simulation"
title = "Isaac Sim Dynamic Control"
description = "Dynamic Control"
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac", "physics"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"omni.physx" = {}
"omni.timeline" = {} # Needed for simulation to occur
"omni.kit.numpy.common" = {}
"omni.usd.libs" = {}
"omni.kit.commands" = {}
"omni.kit.pip_archive" = {} # pulls in numpy
"omni.kit.test" = {}

[[python.module]]
name = "omni.isaac.dynamic_control"

[[python.module]]
name = "omni.isaac.dynamic_control.tests"


[[native.plugin]]
path = "bin/*.plugin"
recursive = false

