[core]
reloadable = true
order = 0

[package]
version = "1.12.2"
category = "Simulation"
title = "ROS2 Humble Bridge"
description = "ROS2 Humble Bridge"
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac", "ROS2"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"

[dependencies]
"omni.kit.uiapp" = {}
"omni.isaac.dynamic_control" = {}
"omni.isaac.range_sensor" = {}
"omni.isaac.core" = {}
"omni.isaac.core_nodes" = {}
"omni.syntheticdata" = {}
"omni.replicator.core" = {}
"omni.usd.schema.isaac" = {}
"omni.graph" = {}
"omni.graph.tools" = {}
"omni.isaac.sensor" = {}
"usdrt.scenegraph" = {}

[[python.module]]
name = "omni.isaac.ros2_bridge"

[[python.module]]
name = "omni.isaac.rclpy"

[[python.module]]
name = "omni.isaac.ros2_bridge.tests"
public = false

[[python.module]]
name = "omni.isaac.ros2_bridge.scripts.samples.ros_samples"

[[python.module]]
name = "omni.isaac.ros2_bridge.scripts.samples.ros_moveit_sample"

# [[native.plugin]]
# path = "bin/omni.isaac.ros2_humble_bridge.plugin"
# recursive = false

[fswatcher.paths]
exclude = ["*/rclpy/*", "*/bin", "*/__pycache__/*", "*/.git/*"]

[fswatcher.patterns]
include = ["*.ogn", "*.py", "*.toml"]
exclude = ["Ogn*Database.py"]

[[test]]
dependencies = [
    "omni.graph.ui",
    "omni.isaac.wheeled_robots",
]

stdoutFailPatterns.exclude = [
    "*WARNING: cannot load logging configuration file*", # exclude warning as failure
    "*[Error] [carb.flatcache.plugin] Error: UsdRelationship * has multiple targets, which is not supported*",
    "*[Error] [omni.graph] Tried to set a value on AttributeData*",
    "*[Error] [omni.graph] AttributeError: Attempted to get array size of non-array attribute inputs:jointNames*",
    "*[Error] [carb.flatcache.plugin] Error: * UsdRelationship not supported in GetPrimArrayAttr*",
    "*[Error] [carb.flatcache.plugin] removePath called on non-existent path*"
]

[[native.library]]
path = "bin/libtinyxml2.so"

[[native.library]]
path = "bin/libactionlib_msgs__rosidl_generator_py.so"
[[native.library]]
path = "bin/libactionlib_msgs__rosidl_generator_c.so"
[[native.library]]
path = "bin/libactionlib_msgs__rosidl_typesupport_c.so"
[[native.library]]
path = "bin/libactionlib_msgs__rosidl_typesupport_fastrtps_c.so"
[[native.library]]
path = "bin/libactionlib_msgs__rosidl_typesupport_introspection_c.so"
[[native.library]]
path = "bin/libaction_msgs__rosidl_generator_c.so"
[[native.library]]
path = "bin/libaction_msgs__rosidl_typesupport_c.so"
[[native.library]]
path = "bin/libaction_msgs__rosidl_typesupport_fastrtps_c.so"
[[native.library]]
path = "bin/libaction_msgs__rosidl_typesupport_introspection_c.so"
[[native.library]]
path = "bin/libbenchmark.so"
[[native.library]]
path = "bin/libbenchmark_main.so"
[[native.library]]
path = "bin/libbuiltin_interfaces__rosidl_generator_c.so"
[[native.library]]
path = "bin/libbuiltin_interfaces__rosidl_typesupport_c.so"
[[native.library]]
path = "bin/libbuiltin_interfaces__rosidl_typesupport_fastrtps_c.so"
[[native.library]]
path = "bin/libbuiltin_interfaces__rosidl_typesupport_introspection_c.so"
[[native.library]]
path = "bin/libclass_loader.so"
[[native.library]]
path = "bin/libcomponent_manager.so"
[[native.library]]
path = "bin/libcomposition_interfaces__rosidl_generator_c.so"
[[native.library]]
path = "bin/libcomposition_interfaces__rosidl_typesupport_c.so"
[[native.library]]
path = "bin/libcomposition_interfaces__rosidl_typesupport_fastrtps_c.so"
[[native.library]]
path = "bin/libcomposition_interfaces__rosidl_typesupport_introspection_c.so"
[[native.library]]
path = "bin/libconsole_bridge.so"
[[native.library]]
path = "bin/libiceoryx_binding_c.so"
[[native.library]]
path = "bin/libddsc.so"
[[native.library]]
path = "bin/libdds_security_ac.so"
[[native.library]]
path = "bin/libdds_security_auth.so"
[[native.library]]
path = "bin/libdds_security_crypto.so"
[[native.library]]
path = "bin/libdiagnostic_msgs__rosidl_generator_c.so"
[[native.library]]
path = "bin/libdiagnostic_msgs__rosidl_typesupport_c.so"
[[native.library]]
path = "bin/libdiagnostic_msgs__rosidl_typesupport_fastrtps_c.so"
[[native.library]]
path = "bin/libdiagnostic_msgs__rosidl_typesupport_introspection_c.so"
[[native.library]]
path = "bin/libfastcdr.so"
[[native.library]]
path = "bin/libfastrtps.so"
[[native.library]]
path = "bin/libgeometry_msgs__rosidl_generator_c.so"
[[native.library]]
path = "bin/libgeometry_msgs__rosidl_typesupport_c.so"
[[native.library]]
path = "bin/libgeometry_msgs__rosidl_typesupport_fastrtps_c.so"
[[native.library]]
path = "bin/libgeometry_msgs__rosidl_typesupport_introspection_c.so"
[[native.library]]
path = "bin/libisaac_ros2_messages__rosidl_generator_c.so"
[[native.library]]
path = "bin/libisaac_ros2_messages__rosidl_typesupport_c.so"
[[native.library]]
path = "bin/libisaac_ros2_messages__rosidl_typesupport_fastrtps_c.so"
[[native.library]]
path = "bin/libisaac_ros2_messages__rosidl_typesupport_introspection_c.so"
[[native.library]]
path = "bin/liblibstatistics_collector.so"
[[native.library]]
path = "bin/liblifecycle_msgs__rosidl_generator_c.so"
[[native.library]]
path = "bin/liblifecycle_msgs__rosidl_typesupport_c.so"
[[native.library]]
path = "bin/liblifecycle_msgs__rosidl_typesupport_fastrtps_c.so"
[[native.library]]
path = "bin/liblifecycle_msgs__rosidl_typesupport_introspection_c.so"
[[native.library]]
path = "bin/libmap_msgs__rosidl_generator_c.so"
[[native.library]]
path = "bin/libmap_msgs__rosidl_typesupport_c.so"
[[native.library]]
path = "bin/libmap_msgs__rosidl_typesupport_fastrtps_c.so"
[[native.library]]
path = "bin/libmap_msgs__rosidl_typesupport_introspection_c.so"
[[native.library]]
path = "bin/libmemory_tools_interpose.so"
[[native.library]]
path = "bin/libmemory_tools.so"
[[native.library]]
path = "bin/libmessage_filters.so"
[[native.library]]
path = "bin/libnav_msgs__rosidl_generator_c.so"
[[native.library]]
path = "bin/libnav_msgs__rosidl_typesupport_c.so"
[[native.library]]
path = "bin/libnav_msgs__rosidl_typesupport_fastrtps_c.so"
[[native.library]]
path = "bin/libnav_msgs__rosidl_typesupport_introspection_c.so"
[[native.library]]
path = "bin/libpcl_msgs__rosidl_generator_c.so"
[[native.library]]
path = "bin/libpcl_msgs__rosidl_typesupport_c.so"
[[native.library]]
path = "bin/libpcl_msgs__rosidl_typesupport_fastrtps_c.so"
[[native.library]]
path = "bin/libpcl_msgs__rosidl_typesupport_introspection_c.so"
[[native.library]]
path = "bin/libpendulum_msgs__rosidl_generator_c.so"
[[native.library]]
path = "bin/libpendulum_msgs__rosidl_typesupport_c.so"
[[native.library]]
path = "bin/libpendulum_msgs__rosidl_typesupport_fastrtps_c.so"
[[native.library]]
path = "bin/libpendulum_msgs__rosidl_typesupport_introspection_c.so"
[[native.library]]
path = "bin/libperformance_test_fixture.so"
[[native.library]]
path = "bin/librcl_action.so"
[[native.library]]
path = "bin/librclcpp_action.so"
[[native.library]]
path = "bin/librclcpp_lifecycle.so"
[[native.library]]
path = "bin/librclcpp.so"
[[native.library]]
path = "bin/librcl_interfaces__rosidl_generator_c.so"
[[native.library]]
path = "bin/librcl_interfaces__rosidl_typesupport_c.so"
[[native.library]]
path = "bin/librcl_interfaces__rosidl_typesupport_fastrtps_c.so"
[[native.library]]
path = "bin/librcl_interfaces__rosidl_typesupport_introspection_c.so"
[[native.library]]
path = "bin/librcl_lifecycle.so"
[[native.library]]
path = "bin/librcl_logging_spdlog.so"
[[native.library]]
path = "bin/librcl.so"
[[native.library]]
path = "bin/librcl_yaml_param_parser.so"
[[native.library]]
path = "bin/librcpputils.so"
[[native.library]]
path = "bin/librcutils.so"
[[native.library]]
path = "bin/librmw_dds_common__rosidl_generator_c.so"
[[native.library]]
path = "bin/librmw_dds_common__rosidl_typesupport_c.so"
[[native.library]]
path = "bin/librmw_dds_common__rosidl_typesupport_fastrtps_c.so"
[[native.library]]
path = "bin/librmw_dds_common__rosidl_typesupport_introspection_c.so"
[[native.library]]
path = "bin/librmw_dds_common.so"
[[native.library]]
path = "bin/librmw_implementation.so"
[[native.library]]
path = "bin/librmw.so"
[[native.library]]
path = "bin/librosgraph_msgs__rosidl_generator_c.so"
[[native.library]]
path = "bin/librosgraph_msgs__rosidl_typesupport_c.so"
[[native.library]]
path = "bin/librosgraph_msgs__rosidl_typesupport_fastrtps_c.so"
[[native.library]]
path = "bin/librosgraph_msgs__rosidl_typesupport_introspection_c.so"
[[native.library]]
path = "bin/librosidl_runtime_c.so"
[[native.library]]
path = "bin/librosidl_typesupport_c.so"
[[native.library]]
path = "bin/librosidl_typesupport_fastrtps_c.so"
[[native.library]]
path = "bin/librosidl_typesupport_introspection_c.so"
[[native.library]]
path = "bin/libsensor_msgs__rosidl_generator_c.so"
[[native.library]]
path = "bin/libsensor_msgs__rosidl_typesupport_c.so"
[[native.library]]
path = "bin/libsensor_msgs__rosidl_typesupport_fastrtps_c.so"
[[native.library]]
path = "bin/libsensor_msgs__rosidl_typesupport_introspection_c.so"
[[native.library]]
path = "bin/libshape_msgs__rosidl_generator_c.so"
[[native.library]]
path = "bin/libshape_msgs__rosidl_typesupport_c.so"
[[native.library]]
path = "bin/libshape_msgs__rosidl_typesupport_fastrtps_c.so"
[[native.library]]
path = "bin/libshape_msgs__rosidl_typesupport_introspection_c.so"
[[native.library]]
path = "bin/libspdlog.so"
[[native.library]]
path = "bin/libstatic_transform_broadcaster_node.so"
[[native.library]]
path = "bin/libstatistics_msgs__rosidl_generator_c.so"
[[native.library]]
path = "bin/libstatistics_msgs__rosidl_typesupport_c.so"
[[native.library]]
path = "bin/libstatistics_msgs__rosidl_typesupport_fastrtps_c.so"
[[native.library]]
path = "bin/libstatistics_msgs__rosidl_typesupport_introspection_c.so"
[[native.library]]
path = "bin/libstd_msgs__rosidl_generator_c.so"
[[native.library]]
path = "bin/libstd_msgs__rosidl_typesupport_c.so"
[[native.library]]
path = "bin/libstd_msgs__rosidl_typesupport_fastrtps_c.so"
[[native.library]]
path = "bin/libstd_msgs__rosidl_typesupport_introspection_c.so"
[[native.library]]
path = "bin/libstd_srvs__rosidl_generator_c.so"
[[native.library]]
path = "bin/libstd_srvs__rosidl_typesupport_c.so"
[[native.library]]
path = "bin/libstd_srvs__rosidl_typesupport_fastrtps_c.so"
[[native.library]]
path = "bin/libstd_srvs__rosidl_typesupport_introspection_c.so"
[[native.library]]
path = "bin/libstereo_msgs__rosidl_generator_c.so"
[[native.library]]
path = "bin/libstereo_msgs__rosidl_typesupport_c.so"
[[native.library]]
path = "bin/libstereo_msgs__rosidl_typesupport_fastrtps_c.so"
[[native.library]]
path = "bin/libstereo_msgs__rosidl_typesupport_introspection_c.so"
[[native.library]]
path = "bin/libtest_msgs__rosidl_generator_c.so"
[[native.library]]
path = "bin/libtest_msgs__rosidl_typesupport_c.so"
[[native.library]]
path = "bin/libtest_msgs__rosidl_typesupport_fastrtps_c.so"
[[native.library]]
path = "bin/libtest_msgs__rosidl_typesupport_introspection_c.so"
[[native.library]]
path = "bin/libtf2_msgs__rosidl_generator_c.so"
[[native.library]]
path = "bin/libtf2_msgs__rosidl_typesupport_c.so"
[[native.library]]
path = "bin/libtf2_msgs__rosidl_typesupport_fastrtps_c.so"
[[native.library]]
path = "bin/libtf2_msgs__rosidl_typesupport_introspection_c.so"
[[native.library]]
path = "bin/libtf2.so"
[[native.library]]
path = "bin/libtracetools.so"
[[native.library]]
path = "bin/libtrajectory_msgs__rosidl_generator_c.so"
[[native.library]]
path = "bin/libtrajectory_msgs__rosidl_typesupport_c.so"
[[native.library]]
path = "bin/libtrajectory_msgs__rosidl_typesupport_fastrtps_c.so"
[[native.library]]
path = "bin/libtrajectory_msgs__rosidl_typesupport_introspection_c.so"
[[native.library]]
path = "bin/libunique_identifier_msgs__rosidl_generator_c.so"
[[native.library]]
path = "bin/libunique_identifier_msgs__rosidl_typesupport_c.so"
[[native.library]]
path = "bin/libunique_identifier_msgs__rosidl_typesupport_fastrtps_c.so"
[[native.library]]
path = "bin/libunique_identifier_msgs__rosidl_typesupport_introspection_c.so"
[[native.library]]
path = "bin/libvision_msgs__rosidl_generator_c.so"
[[native.library]]
path = "bin/libvision_msgs__rosidl_typesupport_c.so"
[[native.library]]
path = "bin/libvision_msgs__rosidl_typesupport_fastrtps_c.so"
[[native.library]]
path = "bin/libvision_msgs__rosidl_typesupport_introspection_c.so"
[[native.library]]
path = "bin/libvisualization_msgs__rosidl_generator_c.so"
[[native.library]]
path = "bin/libvisualization_msgs__rosidl_typesupport_c.so"
[[native.library]]
path = "bin/libvisualization_msgs__rosidl_typesupport_fastrtps_c.so"
[[native.library]]
path = "bin/libvisualization_msgs__rosidl_typesupport_introspection_c.so"
# Python libs
[[native.library]]
path = "bin/libactionlib_msgs__rosidl_generator_py.so"
[[native.library]]
path = "bin/libaction_msgs__rosidl_generator_py.so"
[[native.library]]
path = "bin/libbuiltin_interfaces__rosidl_generator_py.so"
[[native.library]]
path = "bin/libcomposition_interfaces__rosidl_generator_py.so"
[[native.library]]
path = "bin/libdiagnostic_msgs__rosidl_generator_py.so"
[[native.library]]
path = "bin/libexample_interfaces__rosidl_generator_py.so"
[[native.library]]
path = "bin/libgeometry_msgs__rosidl_generator_py.so"
[[native.library]]
path = "bin/libisaac_ros2_messages__rosidl_generator_py.so"
[[native.library]]
path = "bin/liblifecycle_msgs__rosidl_generator_py.so"
[[native.library]]
path = "bin/libmap_msgs__rosidl_generator_py.so"
[[native.library]]
path = "bin/libnav_msgs__rosidl_generator_py.so"
[[native.library]]
path = "bin/libpcl_msgs__rosidl_generator_py.so"
[[native.library]]
path = "bin/libpendulum_msgs__rosidl_generator_py.so"
[[native.library]]
path = "bin/librcl_interfaces__rosidl_generator_py.so"
[[native.library]]
path = "bin/librmw_dds_common__rosidl_generator_py.so"
[[native.library]]
path = "bin/libros2cli_test_interfaces__rosidl_generator_py.so"
[[native.library]]
path = "bin/librosgraph_msgs__rosidl_generator_py.so"
[[native.library]]
path = "bin/libsensor_msgs__rosidl_generator_py.so"
[[native.library]]
path = "bin/libshape_msgs__rosidl_generator_py.so"
[[native.library]]
path = "bin/libstatistics_msgs__rosidl_generator_py.so"
[[native.library]]
path = "bin/libstd_msgs__rosidl_generator_py.so"
[[native.library]]
path = "bin/libstd_srvs__rosidl_generator_py.so"
[[native.library]]
path = "bin/libstereo_msgs__rosidl_generator_py.so"
[[native.library]]
path = "bin/libtest_msgs__rosidl_generator_py.so"
[[native.library]]
path = "bin/libtf2_msgs__rosidl_generator_py.so"
[[native.library]]
path = "bin/libtrajectory_msgs__rosidl_generator_py.so"
[[native.library]]
path = "bin/libunique_identifier_msgs__rosidl_generator_py.so"
[[native.library]]
path = "bin/libvision_msgs__rosidl_generator_py.so"
[[native.library]]
path = "bin/libvisualization_msgs__rosidl_generator_py.so"