# Copyright (c) 2021, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

seed: 123456
step_size: 0.1
max_iterations: 4000
max_sampling: 10000
distance_metric_weights: [3.0, 2.0, 2.0, 1.5, 1.5, 1.0, 1.0]
task_space_frame_name: "panda_rightfingertip"
task_space_limits: [[-0.8, 0.9], [-0.8, 0.8], [0.0, 1.2]]
c_space_planning_params:
  exploration_fraction: 0.5
task_space_planning_params:
  x_target_zone_tolerance: [0.01, 0.01, 0.01]
  x_target_final_tolerance: 1e-5
  task_space_exploitation_fraction: 0.4
  task_space_exploration_fraction: 0.1
