[core]
reloadable = true
order = 0

[package]
version = "1.10.0"
category = "Simulation"
title = "Isaac Sim Tests"
description = "Collection of tests for isaac sim that are not tied to a specific extension"
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac", "tests"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"


[dependencies]
"omni.kit.uiapp" = {}
"omni.physx" = {}
"omni.physx.commands" = {}
"omni.timeline" = {} # needed for simulation to happen
"omni.kit.primitive.mesh" = {} # needed for mesh creation commands
"omni.isaac.core" = {}
"omni.kit.material.library" = {}
"omni.kit.viewport.window" = {} # snippet tests need this
"omni.kit.pip_archive" = {} # pulls in numpy
"omni.syntheticdata" = {}
"omni.isaac.range_sensor" = {}
"omni.isaac.synthetic_utils" = {}
"omni.kit.asset_converter" = {}
"omni.isaac.wheeled_robots" = {}

[[python.module]]
name = "omni.isaac.tests" # so we can find the path to the extension

[[python.module]]
name = "omni.isaac.tests.tests"

[[test]]
timeout = 960
dependencies = [
   "omni.kit.window.toolbar"
]