[core]
reloadable = false
# Load at the start, load all schemas with order -100 (with order -1000 the USD libs are loaded)
order = -100

[package]
version = "1.1.0"
category = "Simulation"
authors = ["NVIDIA"]
title = "USD Isaac schema"
description="USD Isaac schema"
repository = ""
keywords = ["isaac", "usd", "schema"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"omni.usd.libs" = {}
"omni.usd.schema.physics" = {}

[[python.module]]
name = "omni.isaac.RangeSensorSchema"

[[python.module]]
name = "omni.isaac.IsaacSensorSchema"

[[python.module]]
name = "usd.schema.isaac"

[[native.library]]
path = "bin/${lib_prefix}rangeSensorSchema${lib_ext}"

[[native.library]]
path = "bin/${lib_prefix}isaacSensorSchema${lib_ext}"