// Generated by gencpp from file cortex_control/MsgServiceRequest.msg
// DO NOT EDIT!


#ifndef CORTEX_CONTROL_MESSAGE_MSGSERVICEREQUEST_H
#define CORTEX_CONTROL_MESSAGE_MSGSERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cortex_control
{
template <class ContainerAllocator>
struct MsgServiceRequest_
{
  typedef MsgServiceRequest_<ContainerAllocator> Type;

  MsgServiceRequest_()
    : msg()  {
    }
  MsgServiceRequest_(const ContainerAllocator& _alloc)
    : msg(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _msg_type;
  _msg_type msg;





  typedef boost::shared_ptr< ::cortex_control::MsgServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cortex_control::MsgServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MsgServiceRequest_

typedef ::cortex_control::MsgServiceRequest_<std::allocator<void> > MsgServiceRequest;

typedef boost::shared_ptr< ::cortex_control::MsgServiceRequest > MsgServiceRequestPtr;
typedef boost::shared_ptr< ::cortex_control::MsgServiceRequest const> MsgServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cortex_control::MsgServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cortex_control::MsgServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cortex_control::MsgServiceRequest_<ContainerAllocator1> & lhs, const ::cortex_control::MsgServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.msg == rhs.msg;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cortex_control::MsgServiceRequest_<ContainerAllocator1> & lhs, const ::cortex_control::MsgServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cortex_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cortex_control::MsgServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cortex_control::MsgServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cortex_control::MsgServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cortex_control::MsgServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cortex_control::MsgServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cortex_control::MsgServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cortex_control::MsgServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7d96ed730776804754140b85e64c862e";
  }

  static const char* value(const ::cortex_control::MsgServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7d96ed7307768047ULL;
  static const uint64_t static_value2 = 0x54140b85e64c862eULL;
};

template<class ContainerAllocator>
struct DataType< ::cortex_control::MsgServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cortex_control/MsgServiceRequest";
  }

  static const char* value(const ::cortex_control::MsgServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cortex_control::MsgServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# commands sent in json format\n"
"string msg\n"
;
  }

  static const char* value(const ::cortex_control::MsgServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cortex_control::MsgServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cortex_control::MsgServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cortex_control::MsgServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CORTEX_CONTROL_MESSAGE_MSGSERVICEREQUEST_H
