// Generated by gencpp from file cortex_control/MsgService.msg
// DO NOT EDIT!


#ifndef CORTEX_CONTROL_MESSAGE_MSGSERVICE_H
#define CORTEX_CONTROL_MESSAGE_MSGSERVICE_H

#include <ros/service_traits.h>


#include <cortex_control/MsgServiceRequest.h>
#include <cortex_control/MsgServiceResponse.h>


namespace cortex_control
{

struct MsgService
{

typedef MsgServiceRequest Request;
typedef MsgServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MsgService
} // namespace cortex_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cortex_control::MsgService > {
  static const char* value()
  {
    return "38a3da27a00f36b8fc53764490266dcb";
  }

  static const char* value(const ::cortex_control::MsgService&) { return value(); }
};

template<>
struct DataType< ::cortex_control::MsgService > {
  static const char* value()
  {
    return "cortex_control/MsgService";
  }

  static const char* value(const ::cortex_control::MsgService&) { return value(); }
};


// service_traits::MD5Sum< ::cortex_control::MsgServiceRequest> should match
// service_traits::MD5Sum< ::cortex_control::MsgService >
template<>
struct MD5Sum< ::cortex_control::MsgServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cortex_control::MsgService >::value();
  }
  static const char* value(const ::cortex_control::MsgServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cortex_control::MsgServiceRequest> should match
// service_traits::DataType< ::cortex_control::MsgService >
template<>
struct DataType< ::cortex_control::MsgServiceRequest>
{
  static const char* value()
  {
    return DataType< ::cortex_control::MsgService >::value();
  }
  static const char* value(const ::cortex_control::MsgServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cortex_control::MsgServiceResponse> should match
// service_traits::MD5Sum< ::cortex_control::MsgService >
template<>
struct MD5Sum< ::cortex_control::MsgServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cortex_control::MsgService >::value();
  }
  static const char* value(const ::cortex_control::MsgServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cortex_control::MsgServiceResponse> should match
// service_traits::DataType< ::cortex_control::MsgService >
template<>
struct DataType< ::cortex_control::MsgServiceResponse>
{
  static const char* value()
  {
    return DataType< ::cortex_control::MsgService >::value();
  }
  static const char* value(const ::cortex_control::MsgServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CORTEX_CONTROL_MESSAGE_MSGSERVICE_H
